// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukgvvjardofvelpztguj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZ3Z2amFyZG9mdmVscHp0Z3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTg2NDEsImV4cCI6MjA2NTY3NDY0MX0.AEnG5gzgScuOMULX0A0vxw0KEG8t5n0XZazk3i4FNx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);